services:
  stripe-backend:
    build: .
    ports:
      - "8247:8247"
    environment:
      - FLASK_ENV=development
      - LOG_LEVEL=DEBUG
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: