name: Discord Notification
on:
  workflow_run:
    workflows: ["Deploy to Linode (AppleBoy/SSH-Action)"]
    types:
      - completed

jobs:
  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: |
            🚀 **Deployment Complete**
            
            **Status:** ${{ github.event.workflow_run.conclusion == 'success' && '✅ Success' || '❌ Failed' }}
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.event.workflow_run.head_branch }}
            **Commit:** ${{ github.event.workflow_run.head_sha }}
            **Triggered by:** ${{ github.event.workflow_run.triggering_actor.login }}
            
            [View Workflow Run](${{ github.event.workflow_run.html_url }})